### ISSUE TITLE
[Question] How do you access services like nextcloud ?

### ISSUE THREAD

**Issue by blmhemu** [mr-karan/hydra#1]
First of all wonderful writeup at your [blog](https://mrkaran.dev/posts/home-server-updates/)

Coming to the question,
How do you access services like nextcloud when you are outside your private network. I understand that you can access the invidual devices with tailscale, but how to integrate ingress-nginx with tailscale ?
Ex: Say i am connected to multi master HA k3s cluster via tailwind, how do i access my service with simple domain names like 
`nextcloud.myhome.local` 
`bitwarden.myhome.local`
on my laptop / mobile ?

**Comment by mr-karan** [comment]
>  How do you access services like nextcloud when you are outside your private network. I understand that you can access the invidual devices with tailscale, but how to integrate ingress-nginx with tailscale ?

I run `Caddy` web server and that listens on Tailscale IP. My devices (Android phone, iPad) have Tailscale agents installed on them and they can access the Nextcloud server directly (like an overlay mesh, on top of Wireguard).

The setup has gone multiple changes since the last blog post and a new one is due for an update soon. :) 

Thanks!

**Comment by blmhemu** [comment]
Eagerly waiting for a new blog post. A few questions in the meanwhile:
Do tailscale IPs remain constant (static) ?
Also, can you point me to the right files to understand your configuration.

**Comment by mr-karan** [comment]
>  Do tailscale IPs remain constant (static) ?

Yes, for every device they remain the same.

>  Also, can you point me to the right files to understand your configuration.

You can take a look at [this](https://github.com/mr-karan/hydra/blob/master/floyd/terraform/caddy/network.tf) and [this](https://github.com/mr-karan/hydra/blob/master/floyd/terraform/gitea/container.tf#L29). I create 2 separate Caddy containers for Private/Public sites. These 2 containers have their own docker networks. For any site that I want to use private only, I attach the container to the Caddy private docker network.

>  Also how do you point the custom domain name to the tailwinds ip ?

I use Cloudflare for this. Setup an A record pointing to a private Tailscale IP.
