### ISSUE TITLE
Nomad in sinlge node in dev!

### ISSUE THREAD

**Issue by pratikbalar** [mr-karan/hydra#7]
Just found your blog post when searching for nomad style self hosting and loving it.

Question, did not get this [https://github.com/mr-karan/hydra/blob/master/docs/SETUP.md#configurations](https://github.com/mr-karan/hydra/blob/master/docs/SETUP.md#configurations) part, are you running nomad in single server if yes then is it in `-dev` mode?, kindly explain.

2nd Any reasons to not use consul? 

waiting for valut thing, huge fan of Zerodha as well it's tech infra. Thank you.

**Comment by mr-karan** [comment]
> are you running nomad in single server

Yes

> if yes then is it in -dev mode?,

No. Running it as a single server/client on the same machine. `-dev` is only good for quick tests, no state is persisted.

> Any reasons to not use consul

I'm using it: https://github.com/mr-karan/hydra/blob/master/docs/SETUP.md#setup-consul

**Comment by pratikbalar** [comment]
> I'm using it:..

Ahhh 🙈
